### ISSUE TITLE
Conflict between naming Facility and Facilities

### ISSUE THREAD

**Issue by ayush0x00** [LibreHealthIO/lh-ehr-laravel#14]
**Describe the bug**
There are some scripts where folder name Facility is used and in code it is named app/Facilities which is causing error during 
migration of seed.
**To Reproduce**
Just follow the installation process of current codebase.

**Screenshot**
![Screenshot from 2020-11-22 03-50-16](https://user-images.githubusercontent.com/44584229/99888933-93a8ac00-2c76-11eb-8989-b3610151dab6.png)

**Expected behavior**
The codebase should have successfully migrated the seed.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Brave

**Comment by ayush0x00** [comment]
I would like to work on this issue.

**Comment by muarachmann** [comment]
> I would like to work on this issue.

Nice catch go ahead!

**Comment by ayush0x00** [comment]
The conflict started after the commit `c4bbed6`. Resetting back to `c4bbed6` just before running `php artisan migrate --seed` solves the issue. However, this isn't a solution to the issue.

**Comment by ayush0x00** [comment]
Where is this error coming from? I have searched the whole project, `app\Helper\` is nowhere to be found. I had to rename `app\` to `App\` to solve some path conflicts. And then i made sure to update the change to everywhere. Still, I am getting errors. 
@muarachmann could you please look in this.


![Screenshot from 2020-11-22 19-55-32](https://user-images.githubusercontent.com/44584229/99906582-ec6f5780-2cfd-11eb-81ce-e274d663395f.png)

**Comment by muarachmann** [comment]
I dont have this issue, the app/Helpers is correct, try to get the latest codes and let me know if this persist.

**Comment by ayush0x00** [comment]
@muarachmann there is a lot of naming conflicts. Changing them, changes the whole codebase with quite a bunch of errors. I think we might have to revert back to a previous commit. How did the code get to run in the first place???.
Sorry for late reply, my end term exams are going on.

**Comment by muarachmann** [comment]
No hurrying here, school first and best of lucks

**Comment by muarachmann** [comment]
Fixed
