### ISSUE TITLE
Broken link for Contribution guide, change log and troubleshooting guide 

### ISSUE THREAD

**Issue by prondubuisi** [LibreHealthIO/lh-ehr-laravel#2]
**Describe the bug**
The Readme link for the above are all broken

**Comment by muarachmann** [comment]
Sure this will be enhanced accordingly .

**Comment by aakash-gorai** [comment]
what to do in this issue I want to contribute please guide me

**Comment by muarachmann** [comment]
Hi @aakash-kumar-gorai welcome to LH and thanks for your interest.
Have you cloned and installed the project already and also you can join the [forums](https://forums.librehealth.io/t/librehealth-ehr-porting-to-laravel-8/3807) here to get in details how to contribute to this repo.

**Comment by aakash-gorai** [comment]
yes I have forked this repo and what to do ?

**Comment by muarachmann** [comment]
Sorry for the late reply. @aakash-kumar-gorai still interest to contribute to this. Please join here https://forums.librehealth.io/t/librehealth-ehr-porting-to-laravel-8/3807

**Comment by muarachmann** [comment]
Hello @aakash-gorai sorry for the late response.
Still interested in this?

**Comment by rukundob451** [comment]
Has anyone started contributing to this issue?

**Comment by muarachmann** [comment]
Hi @rukundob451 we actually don't have those sections yet. I will invite you to first install the https://github.com/LibreHealthIO/lh-ehr from there you will have a better understanding of how the system works then contribute accordingly.

Regards

**Comment by vaibhavrawat24** [comment]
hi @muarachmann  can I work on this issue?

**Comment by muarachmann** [comment]
Hi @vaibhavrawat24 sure you can. 

And then  as primary task I will invite you do this first and post your screen as stated here #27

**Comment by vaibhavrawat24** [comment]
Sure @muarachmann !

**Comment by vaibhavrawat24** [comment]
@muarachmann can you help me ? I've cloned the repo , I need help in understanding how to setup as I'm new to open source

**Comment by prondubuisi** [comment]
Hello @vaibhavrawat24 there is a set up guide, follow the instructions here https://github.com/LibreHealthIO/lh-ehr-laravel#installation

**Comment by chaitak-gorai** [comment]
hi @prondubuisi @muarachmann 
I have done the initial setup #27 
Can i move forward to solve this issue?

**Comment by muarachmann** [comment]
Yes please which project are you interested in? Comment on the thread in the forums for clarity

**Comment by chaitak-gorai** [comment]
I am interested in the "Migrating EHR to Laravel for User Module"  project. I have mentioned it in forums too. 

Thank you.
