### ISSUE TITLE
the storage file is ignored!

### ISSUE THREAD

**Issue by jehadja** [LibreHealthIO/lh-ehr-laravel#26]
**Describe the bug**
the storage folder is ignored, we need to add to the documentation how to add these folders and their subfolders framework/cache, etc... moreover, it will not complete the installation as it needs file to exist on the storage 
`lh-ehr-laravel/storage/app/public/ehr_installer.json): failed to open stream: No such file or directory
`
 moreover composer install not found token for GitHub for vue-i18n-generator

**Comment by muarachmann** [comment]
Hi @jehadja sorry for the late reply & thanks for the notice...  yes you are actually right.
Will fix this. 

Regards

**Comment by muarachmann** [comment]
Hello @jehadja fixed. Also migrated to L9.
Let me know if you encounter any issues and I will reopen this
